import { Command } from 'commander';
import { mkdirSync } from 'node:fs';
import { writeFileSync } from 'atomically';
import { resolve } from 'node:path';
import pc from 'picocolors';
import { getRepoRoot } from '../lib/git.js';
import { listDocs, readDoc } from '../lib/docs.js';
import { syncDocs } from '../lib/doc-sync.js';
import { ensurePawGitignore, removePawFromRootGitignore } from '../lib/gitignore.js';
import { installHooks } from '../lib/hooks.js';
import { success, skip, handleError } from '../lib/output.js';

const DO_NOT_EDIT_MARKER =
  '<!-- DO NOT EDIT: Generated by paw init.\nRun `paw init` to update. -->';

/** Generate a resource directory table from doc frontmatter. */
function generateDirectoryTable(category: string, command: string): string {
  const docs = listDocs(category);
  // Exclude internal templates (skill files and role-specific briefs used by prime)
  const filtered = docs.filter((d) => !d.name.startsWith('skill') && !d.name.endsWith('-brief'));
  const rows = filtered.map(
    (d) => `| \`paw ${command} ${d.name}\` | ${d.description || d.title} |`,
  );
  return ['| Command | Purpose |', '|---|---|', ...rows].join('\n');
}

/** Replace content between HTML markers in skill content with generated tables. */
function injectDirectories(content: string): string {
  const replacements: [string, string, string, string][] = [
    [
      '<!-- BEGIN SHORTCUT DIRECTORY -->',
      '<!-- END SHORTCUT DIRECTORY -->',
      'shortcuts',
      'shortcut',
    ],
    [
      '<!-- BEGIN GUIDELINES DIRECTORY -->',
      '<!-- END GUIDELINES DIRECTORY -->',
      'guidelines',
      'guidelines',
    ],
    [
      '<!-- BEGIN TEMPLATE DIRECTORY -->',
      '<!-- END TEMPLATE DIRECTORY -->',
      'templates',
      'template',
    ],
  ];

  let result = content;
  for (const [beginMarker, endMarker, category, cmd] of replacements) {
    const beginIdx = result.indexOf(beginMarker);
    const endIdx = result.indexOf(endMarker);
    if (beginIdx !== -1 && endIdx !== -1) {
      const table = generateDirectoryTable(category, cmd);
      result =
        result.slice(0, beginIdx + beginMarker.length) + '\n' + table + '\n' + result.slice(endIdx);
    }
  }
  return result;
}

export function initCommand(): Command {
  return new Command('init').description('Initialize paw in a repo').action(() => {
    try {
      const repoRoot = getRepoRoot();

      console.log(pc.bold('paw init\n'));

      // Sync bundled docs to .paw/docs/ (must run before SKILL.md generation)
      try {
        const syncResult = syncDocs(repoRoot);
        if (syncResult.added.length > 0 || syncResult.updated.length > 0) {
          const parts: string[] = [];
          if (syncResult.added.length > 0) parts.push(`${syncResult.added.length} new`);
          if (syncResult.updated.length > 0) parts.push(`${syncResult.updated.length} updated`);
          if (syncResult.removed.length > 0) parts.push(`${syncResult.removed.length} removed`);
          success('docs', `synced (${parts.join(', ')})`);
        } else {
          success('docs', 'up to date');
        }
      } catch {
        skip('docs', 'bundled docs not found (run pnpm build)');
      }

      // Write skill file from bundled template
      const skillDir = resolve(repoRoot, '.claude', 'skills', 'paw');
      const skillPath = resolve(skillDir, 'SKILL.md');
      mkdirSync(skillDir, { recursive: true });
      const skillDoc = readDoc('templates', 'skill');
      if (!skillDoc) {
        skip('skill', 'template not found (run pnpm build)');
      } else {
        let skillContent = skillDoc.content.replace(
          /^(---\n[\s\S]*?\n---\n)/,
          `$1${DO_NOT_EDIT_MARKER}\n`,
        );
        skillContent = injectDirectories(skillContent);
        writeFileSync(skillPath, skillContent, 'utf-8');
        success('skill', skillPath);
      }

      // Migrate from root .gitignore (.paw/ entry) to .paw/.gitignore
      if (removePawFromRootGitignore(repoRoot)) {
        success('gitignore', 'migrated — removed .paw/ from root .gitignore');
      }
      if (ensurePawGitignore(repoRoot)) {
        success('gitignore', 'created .paw/.gitignore');
      } else {
        skip('gitignore', '.paw/.gitignore up to date');
      }

      // Write .paw/paw.yaml from bundled template (always refresh on setup)
      try {
        const pawYamlDoc = readDoc('templates', 'paw-yaml');
        if (pawYamlDoc) {
          const yamlMatch = pawYamlDoc.content.match(/```yaml\r?\n([\s\S]*?)```/);
          if (yamlMatch) {
            const configDir = resolve(repoRoot, '.paw');
            mkdirSync(configDir, { recursive: true });
            writeFileSync(resolve(configDir, 'paw.yaml'), yamlMatch[1]);
            success('config', resolve(configDir, 'paw.yaml'));
          }
        }
      } catch {
        skip('config', 'paw-yaml template not found (run pnpm build)');
      }

      // Create .paw/hooks/ directory for user hook scripts
      const hooksDir = resolve(repoRoot, '.paw', 'hooks');
      mkdirSync(hooksDir, { recursive: true });
      success('hooks', hooksDir);

      // Install Claude Code hooks and wrapper script
      installHooks(repoRoot);

      console.log(pc.dim('\nEdit .paw/paw.yaml and run `paw go` to start a session.'));
    } catch (err) {
      handleError(err);
    }
  });
}
