import { Command } from 'commander';
import { existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { writeFileSync } from 'atomically';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import pc from 'picocolors';
import { getRepoRoot } from '../lib/git.js';
import { listDocs } from '../lib/docs.js';
import { syncDocs } from '../lib/doc-sync.js';
import { ensureFleetGitignore, removeFleetFromRootGitignore } from '../lib/gitignore.js';
import { installHooks } from '../lib/hooks.js';
import { success, skip, handleError } from '../lib/output.js';
import { findBundledDir, writeDefaultFleetYaml } from '../lib/util.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const DO_NOT_EDIT_MARKER =
  '<!-- DO NOT EDIT: Generated by fleet init.\nRun `fleet init` to update. -->';

const ROLES = ['orchestrator', 'builder', 'reviewer'] as const;

/** Generate a role-filtered directory table from doc frontmatter. */
function generateDirectoryTable(category: string, command: string, role: string): string {
  const docs = listDocs(category);
  const filtered = docs.filter((d) => {
    if (d.name.startsWith('skill') || d.name.endsWith('-brief')) return false;
    if (!d.roles || d.roles.length === 0) return true;
    return d.roles.includes(role);
  });
  const rows = filtered.map(
    (d) => `| \`fleet ${command} ${d.name}\` | ${d.description || d.title} |`,
  );
  return ['| Command | Purpose |', '|---|---|', ...rows].join('\n');
}

/** Replace content between HTML markers with role-filtered directory tables. */
function injectDirectories(content: string, role: string): string {
  const replacements: [string, string, string, string][] = [
    [
      '<!-- BEGIN SHORTCUT DIRECTORY -->',
      '<!-- END SHORTCUT DIRECTORY -->',
      'shortcuts',
      'shortcut',
    ],
    [
      '<!-- BEGIN GUIDELINES DIRECTORY -->',
      '<!-- END GUIDELINES DIRECTORY -->',
      'guidelines',
      'guidelines',
    ],
    [
      '<!-- BEGIN TEMPLATE DIRECTORY -->',
      '<!-- END TEMPLATE DIRECTORY -->',
      'templates',
      'template',
    ],
  ];

  let result = content;
  for (const [beginMarker, endMarker, category, cmd] of replacements) {
    const beginIdx = result.indexOf(beginMarker);
    const endIdx = result.indexOf(endMarker);
    if (beginIdx !== -1 && endIdx !== -1) {
      const table = generateDirectoryTable(category, cmd, role);
      result =
        result.slice(0, beginIdx + beginMarker.length) + '\n' + table + '\n' + result.slice(endIdx);
    }
  }
  return result;
}

/**
 * Resolve the skills source directory. Checks dist/skills/ first,
 * falls back to repo root skills/ for local development.
 */
function getSkillsBasePath(): string | null {
  return findBundledDir(__dirname, 'skills');
}

/** Read a role-specific skill source file. */
function readSkillSource(role: string): string | null {
  const basePath = getSkillsBasePath();
  if (!basePath) return null;
  const skillPath = resolve(basePath, role, 'SKILL.md');
  if (!existsSync(skillPath)) return null;
  return readFileSync(skillPath, 'utf-8');
}

/** Install role-specific skills and clean up the old monolithic skill. */
function installSkills(repoRoot: string): void {
  let installed = 0;

  for (const role of ROLES) {
    const source = readSkillSource(role);
    if (!source) continue;

    const skillDir = resolve(repoRoot, '.claude', 'skills', role);
    mkdirSync(skillDir, { recursive: true });

    let content = source.replace(/^(---\n[\s\S]*?\n---\n)/, `$1${DO_NOT_EDIT_MARKER}\n`);
    content = injectDirectories(content, role);

    writeFileSync(resolve(skillDir, 'SKILL.md'), content, 'utf-8');
    installed++;
  }

  if (installed > 0) {
    success('skills', `${installed} role-specific skills installed`);
  } else {
    skip('skills', 'skill sources not found (run pnpm build)');
  }

  const oldSkillDir = resolve(repoRoot, '.claude', 'skills', 'fleet');
  if (existsSync(oldSkillDir)) {
    rmSync(oldSkillDir, { recursive: true, force: true });
  }
}

/** CLI command: initialize fleet in a repository (sync docs, write skills, install hooks). */
export function initCommand(): Command {
  return new Command('init').description('Initialize fleet in a repo').action(() => {
    try {
      const repoRoot = getRepoRoot();

      console.log(pc.bold('fleet init\n'));

      try {
        const syncResult = syncDocs(repoRoot);
        if (syncResult.added.length > 0 || syncResult.updated.length > 0) {
          const parts: string[] = [];
          if (syncResult.added.length > 0) parts.push(`${syncResult.added.length} new`);
          if (syncResult.updated.length > 0) parts.push(`${syncResult.updated.length} updated`);
          if (syncResult.removed.length > 0) parts.push(`${syncResult.removed.length} removed`);
          success('docs', `synced (${parts.join(', ')})`);
        } else {
          success('docs', 'up to date');
        }
      } catch (err) {
        skip('docs', `sync failed: ${err instanceof Error ? err.message : String(err)}`);
      }

      installSkills(repoRoot);

      if (removeFleetFromRootGitignore(repoRoot)) {
        success('gitignore', 'migrated — removed .fleet/ from root .gitignore');
      }
      if (ensureFleetGitignore(repoRoot)) {
        success('gitignore', 'created .fleet/.gitignore');
      } else {
        skip('gitignore', '.fleet/.gitignore up to date');
      }

      try {
        if (writeDefaultFleetYaml(repoRoot)) {
          success('config', resolve(repoRoot, '.fleet', 'fleet.yaml'));
        }
      } catch {
        skip('config', 'fleet-yaml template not found (run pnpm build)');
      }

      installHooks(repoRoot);

      console.log(pc.dim('\nEdit .fleet/fleet.yaml and run `fleet go` to start a session.'));
    } catch (err) {
      handleError(err);
    }
  });
}
