import { Command } from 'commander';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import pc from 'picocolors';
import { getRepoRoot } from '../lib/git.js';
import { getDocsBasePath, readDoc } from '../lib/docs.js';
import { installHooks } from '../lib/hooks.js';
import { success, skip, handleError } from '../lib/output.js';

const DO_NOT_EDIT_MARKER =
  '<!-- DO NOT EDIT: Generated by paw setup.\nRun `paw setup` to update. -->';
const PAW_BEGIN_MARKER = '<!-- DO NOT EDIT: Generated by paw setup.';

/** Strip YAML frontmatter (--- block ---) from markdown content. */
function stripFrontmatter(content: string): string {
  return content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '');
}

/** Get SKILL.md content wrapped in DO NOT EDIT markers for AGENTS.md injection. */
function getPawSection(skillContent: string): string {
  const stripped = stripFrontmatter(skillContent);
  return `${DO_NOT_EDIT_MARKER}\n\n${stripped}`;
}

/** Replace the marker-delimited paw section in existing content. */
function updatePawSection(content: string, pawSection: string): string {
  const startIdx = content.indexOf(PAW_BEGIN_MARKER);
  if (startIdx === -1) {
    return content;
  }
  return content.slice(0, startIdx) + pawSection;
}

/** Create or update AGENTS.md with paw skill content. */
function installAgentsSection(repoRoot: string, skillContent: string): void {
  const agentsPath = resolve(repoRoot, 'AGENTS.md');
  const pawSection = getPawSection(skillContent);

  if (existsSync(agentsPath)) {
    const existing = readFileSync(agentsPath, 'utf-8');
    if (existing.includes(PAW_BEGIN_MARKER)) {
      writeFileSync(agentsPath, updatePawSection(existing, pawSection), 'utf-8');
      success('agents', 'updated paw section in AGENTS.md');
    } else {
      const separator = existing.endsWith('\n') ? '\n' : '\n\n';
      writeFileSync(agentsPath, existing + separator + pawSection, 'utf-8');
      success('agents', 'added paw section to existing AGENTS.md');
    }
  } else {
    writeFileSync(agentsPath, pawSection, 'utf-8');
    success('agents', 'created AGENTS.md');
  }
}

export function setupCommand(): Command {
  return new Command('setup').description('Initialize paw in a repo').action(() => {
    try {
      const repoRoot = getRepoRoot();

      console.log(pc.bold('paw setup\n'));

      // Write skill file from bundled template
      const skillDir = resolve(repoRoot, '.claude', 'skills', 'paw');
      const skillPath = resolve(skillDir, 'SKILL.md');
      mkdirSync(skillDir, { recursive: true });
      const skillDoc = readDoc('templates', 'skill');
      if (!skillDoc) {
        skip('skill', 'template not found (run pnpm build)');
      } else {
        const skillContent = skillDoc.content.replace(
          /^(---\n[\s\S]*?\n---\n)/,
          `$1${DO_NOT_EDIT_MARKER}\n`,
        );
        writeFileSync(skillPath, skillContent, 'utf-8');
        success('skill', skillPath);
      }

      // Create/update AGENTS.md with paw skill content
      if (skillDoc) {
        installAgentsSection(repoRoot, skillDoc.content);
      }

      // Ensure .paw/ is in .gitignore
      const gitignorePath = resolve(repoRoot, '.gitignore');
      let gitignore = '';
      if (existsSync(gitignorePath)) {
        gitignore = readFileSync(gitignorePath, 'utf-8');
      }

      const gitignoreEntries = ['.paw/'];
      const missing = gitignoreEntries.filter((entry) => !gitignore.includes(entry));

      if (missing.length === 0) {
        skip('gitignore', 'paw entries already present');
      } else {
        const separator = gitignore.length > 0 && !gitignore.endsWith('\n') ? '\n' : '';
        const comment = gitignore.includes('# paw working state') ? '' : '\n# paw working state\n';
        const block = missing.join('\n');
        writeFileSync(gitignorePath, gitignore + separator + comment + block + '\n', 'utf-8');
        success('gitignore', `added ${missing.join(', ')}`);
      }

      // Copy bundled docs to .paw/docs/ (clean first to remove stale files)
      try {
        const docsBase = getDocsBasePath();
        const destDocs = resolve(repoRoot, '.paw', 'docs');
        if (existsSync(destDocs)) {
          rmSync(destDocs, { recursive: true });
        }
        cpSync(docsBase, destDocs, { recursive: true });
        success('docs', destDocs);
      } catch {
        // Docs may not be available in dev without a build
        skip('docs', 'bundled docs not found (run pnpm build)');
      }

      // Write .paw/paw.yaml from bundled template (always refresh on setup)
      try {
        const pawYamlDoc = readDoc('templates', 'paw-yaml');
        if (pawYamlDoc) {
          const yamlMatch = pawYamlDoc.content.match(/```yaml\r?\n([\s\S]*?)```/);
          if (yamlMatch) {
            const configDir = resolve(repoRoot, '.paw');
            mkdirSync(configDir, { recursive: true });
            writeFileSync(resolve(configDir, 'paw.yaml'), yamlMatch[1]!);
            success('config', resolve(configDir, 'paw.yaml'));
          }
        }
      } catch {
        skip('config', 'paw-yaml template not found (run pnpm build)');
      }

      // Install Claude Code hooks and wrapper script
      installHooks(repoRoot);

      console.log(pc.dim('\nEdit .paw/paw.yaml and run `paw up` to start a session.'));
    } catch (err) {
      handleError(err);
    }
  });
}
