import { Command } from "commander";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { resolve } from "node:path";
import pc from "picocolors";
import { getRepoRoot } from "../lib/git.js";
import { getDocsBasePath, readDoc } from "../lib/docs.js";
import { installHooks } from "../lib/hooks.js";
import { success, skip, handleError } from "../lib/output.js";

const DO_NOT_EDIT_MARKER =
  "<!-- DO NOT EDIT: Generated by paw setup. Run paw setup to update. -->";

export function setupCommand(): Command {
  return new Command("setup")
    .description("Initialize paw in a repo")
    .action(() => {
      try {
        const repoRoot = getRepoRoot();

        console.log(pc.bold("paw setup\n"));

        // Write skill file from bundled template
        const skillDir = resolve(repoRoot, ".claude", "skills", "paw");
        const skillPath = resolve(skillDir, "SKILL.md");
        mkdirSync(skillDir, { recursive: true });
        const skillDoc = readDoc("templates", "skill");
        if (!skillDoc) {
          skip("skill", "template not found (run pnpm build)");
        } else {
          const skillContent = skillDoc.content.replace(
            /^(---\n[\s\S]*?\n---\n)/,
            `$1${DO_NOT_EDIT_MARKER}\n`,
          );
          writeFileSync(skillPath, skillContent, "utf-8");
          success("skill", skillPath);
        }

        // Ensure .paw/ is in .gitignore
        const gitignorePath = resolve(repoRoot, ".gitignore");
        let gitignore = "";
        if (existsSync(gitignorePath)) {
          gitignore = readFileSync(gitignorePath, "utf-8");
        }

        const gitignoreEntries = [".paw/", "paw.yaml", "paw.yml"];
        const missing = gitignoreEntries.filter(
          (entry) => !gitignore.includes(entry),
        );

        if (missing.length === 0) {
          skip("gitignore", "paw entries already present");
        } else {
          const separator =
            gitignore.length > 0 && !gitignore.endsWith("\n") ? "\n" : "";
          const comment = gitignore.includes("# paw working state")
            ? ""
            : "\n# paw working state\n";
          const block = missing.join("\n");
          writeFileSync(
            gitignorePath,
            gitignore + separator + comment + block + "\n",
            "utf-8",
          );
          success("gitignore", `added ${missing.join(", ")}`);
        }

        // Copy bundled docs to .paw/docs/ (clean first to remove stale files)
        try {
          const docsBase = getDocsBasePath();
          const destDocs = resolve(repoRoot, ".paw", "docs");
          if (existsSync(destDocs)) {
            rmSync(destDocs, { recursive: true });
          }
          cpSync(docsBase, destDocs, { recursive: true });
          success("docs", destDocs);
        } catch {
          // Docs may not be available in dev without a build
          skip("docs", "bundled docs not found (run pnpm build)");
        }

        // Install Claude Code hooks and wrapper script
        installHooks(repoRoot);

        console.log(
          pc.dim("\nCreate a paw.yaml and run `paw up` to start a session."),
        );
      } catch (err) {
        handleError(err);
      }
    });
}
